In [ ]:
!pip install requests beautifulsoup4 pandas

Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (2.32.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.13/dist-packages (4.13.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests) (2026.10.19)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (3.0.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (4.16.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [ ]:
url="http://books.toscrape.com/"
response = requests.get(url)
print("Status Code:",response.status_code)

Status Code: 200

In [ ]:
soup = BeautifulSoup(response.text,"html.parser")
books = soup.find_all("article", class_="product_pod")
print("Total Books found:", len(books))

Total Books found: 20

In [ ]:
first_book=books[0]
title=first_book.h3.a['title']
price=first_book.find('p',class_="price_color").text
print("Title:", title)
print("Price:", price)

Title: A Light in the Attic
Price: Â£51.77

In [ ]:
page_data=[]
for book in books:
  title=book.h3.a['title']
  price_text= book.find('p',class_="price_color").text
  price= float(price_text.replace("£","").replace("Â",""))
  availability= book.find('p',class_="instock availability").text.strip()
  rating=book.p["class"][1]
  page_data.append({
      "title":title,
      "price_gbp":price,
      "availability": availability,
      "rating": rating
  })
print(f"Successfully collected {len(page_data)} books!")

Successfully collected 20 books!

In [ ]:
df_page1 = pd.DataFrame(page_data)
df_page1.head()

                                   title  price_gbp availability rating
0                   A Light in the Attic      51.77     In stock  Three
1                     Tipping the Velvet      53.74     In stock    One
2                             Soumission      50.10     In stock    One
3                          Sharp Objects      47.82     In stock   Four
4  Sapiens: A Brief History of Humankind      54.23     In stock   Five

In [ ]:
all_products=[]
for page in range(1,6):
  url=f"http://books.toscrape.com/catalogue/page-{page}.html"
  response=requests.get(url)

  if response.status_code==200:
    soup=BeautifulSoup(response.text,"html.parser")
    book_list=soup.find_all("article",class_="product_pod")
    for book in book_list:
            title = book.h3.a["title"]

            price_text = book.find("p", class_="price_color").text
            price = float(price_text.replace("£", "").replace("Â", ""))

            availability = book.find("p", class_="instock availability").text.strip()

            rating = book.p["class"][1]

            all_products.append({
                "title": title,
                "price_gbp": price,
                "availability": availability,
                "rating": rating,
                "page_number": page
            })
            print(f"Page Scraped Successfully.")
print(f"\nTotal Dataset Size: {len(all_products)} products collected.")

Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.
Page Scraped Successfully.

Total Dataset Size: 100 products collected.

In [ ]:
df_all= pd.DataFrame(all_products)
df_all.to_csv("raw_ecommerce_data.csv",index=False)
print("Dataset Shape(Rows, Columns):", df_all.shape)
df_all.head()

Dataset Shape(Rows, Columns): (100, 5)

,title,price_gbp,availability,rating,page_number
0,A Light in the Attic,51.77,In stock,Three,1
1,Tipping the Velvet,53.74,In stock,One,1
2,Soumission,50.10,In stock,One,1
3,Sharp Objects,47.82,In stock,Four,1
4,Sapiens: A Brief History of Humankind,54.23,In stock,Five,1